apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: hello-train
  annotations:
    scenarios.ai.sap.com/name: "hello-ai"
    scenarios.ai.sap.com/description: "Hello world scenario"
    executables.ai.sap.com/name: "hello-train"
    executables.ai.sap.com/description: "Simple hello world executable"

labels:
  scenarios.ai.sap.com/id: "hello-ai"
  ai.sap.com/version: "1.0.0"
  ai.sap.com/resourcePlan: "starter"

spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: alpine:3.19
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Hello from SAP AI Core Workflow!"
            sleep 5
